### ISSUE TITLE
about PyTorch version

### ISSUE THREAD

**Issue by mychina75** [bobqywei/inpainting-partial-conv#4]
Hi, 
Thank you for your work.
which version of PyTorch is used? 
I met with some strange error when trying it.

##################
Loaded model to device...
Setup Adam optimizer...
Setup loss function...

EPOCH:0 of 3 - starting training loop from iteration:0 to iteration:10625

  0%|          | 0/10625 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/code/inpainting/inpainting-partial-conv/train.py", line 143, in <module>
    output = model(image, mask)
  File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/code/inpainting/inpainting-partial-conv/partial_conv_net.py", line 150, in forward
    encoder_dict[key], mask_dict[key] = getattr(self, encoder_key)(encoder_dict[key_prev], mask_dict[key_prev])
  File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/code/inpainting/inpainting-partial-conv/partial_conv_net.py", line 53, in forward
    output = self.input_conv((input_x * mask))
  File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: expected stride to be a single integer value or a list of 3 values to match the convolution dimensions, but got stride=[2, 2]

Process finished with exit code 1

**Comment by bobqywei** [comment]
@mychina75 Should be PyTorch 1.0.0. I was using the default PyTorch disk image on Google compute engine. Hmm, can you print out the input image dimensions prior to forward pass?

**Comment by erhuodaosi** [comment]
Hi,have you worked it out?
while training the model,I have met a question that I can not solve:
(py3) [fl@ibcu05 place2]$ python train.py
Loaded training dataset with 1434892 samples and 55116 masks
Loaded model to device...
Setup Adam optimizer...
Setup loss function...

EPOCH:0 of 3 - starting training loop from iteration:0 to iteration:89680

0%| | 0/89680 [00:00<?, ?it/s]
Traceback (most recent call last):
File "train.py", line 141, in
loss_dict = loss_func(image, mask, output, gt)
File "/home/fl/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "/home/fl/place2/loss.py", line 94, in forward
loss_dict["tv"] = total_variation_loss(composed_output, self.l1) * LAMBDAS["tv"]
File "/home/fl/place2/loss.py", line 50, in total_variation_loss
loss = l1(image[:, :, :, :-1] - image[:, :, :, 1:]) + l1(image[:, :, :-1, :] - image[:, :, 1:, :])
File "/home/fl/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'target'

I would very appreciate if you could help me, thank you!

**Comment by bobqywei** [comment]
Nevermind, this code was written a while ago with Pytorch 0.4.0. Will try to update soon potentially.
